--- #YAML:1.0
name:                Acme-StringFormat
version:             0.01
abstract:            Smart interface to sprintf()
license:             perl
author:              
    - Goro Fuji  <gfuji (at) cpan.org >
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
